Test Bench
==========

TestBench is a testing framework for Ruby aiming to offer precisely what is needed to test well-designed code effectively and easily. In stark contrast to most other testing frameworks, test files are written using a procedural API, not a declarative one, which brings a score of substantial benefits in exchange for largely immaterial drawbacks. As a result, TestBench can be learned very quickly. However, users should not expect it to offer many palliative features that ease the difficulties inherent to working with vast, long-running, or brittle test suites. With that in mind, even those situations can usually be addressed with a little improvising.

Quick Start Guide
-----------------

To install TestBench locally with rubygems:

[source]
----
> gem install test_bench
----

Or, to add it to a project's +Gemfile+ if using Bundler:

[source]
----
gem 'test_bench'
----

Next, write a test loader, e.g. +test/test_init.rb+:

[source,ruby]
----
# Begin test/test_init.rb

# Load Test Bench and then activate it
require 'test_bench'; TestBench.activate

# Load the code to be tested
require_relative '../lib/my/code.rb'

# End test/test_init.rb
----

Then add test files that require the test loader via +require_relative+. The typical directory to store test files is +test/automated+. For example:

[source,ruby]
----
# Begin test/automated/some_test_file.rb

require_relative '../test_init'

context "Some Context" do
  test "Some test" do
    assert(true)
  end

  context "Inner Context" do
    test "Some other test" do
      assert(false) # will fail!
    end
  end
end

# End test/automated/some_test_file.rb
----

The above test file can be run directly by ruby:
[source]
----
> ruby test/automated/some_test_file.rb 
Some Context
  Some test
  Inner Context
    Some other test
      test/automated/some_test_file.rb:12:in `block (3 levels) in <main>': Assertion failed (TestBench::Fixture::AssertionFailure)

----

To run all the tests within the +test/automated+ directory, the TestBench CLI can be used. The TestBench gem doesn't include an executable, so invoke the CLI from a file within the project (commonly +test/automated.rb+):

[source,ruby]
----
# Begin test/automated.rb

require_relative './test_init'

TestBench::CLI.()

# End test/automated.rb
----

Now use ruby to run the CLI:

[source]
----
> ruby test/automated.rb
Running test/automated/some_test_file.rb
Some Context
  Some test
  Inner Context
    Some other test
      test/automated/some_test_file.rb:12:in `block (4 levels) in load': Assertion failed (TestBench::Fixture::AssertionFailure)

Error Summary:
   1: test/automated/some_test_file.rb

Finished running 1 file
Ran 2 tests in 0.000s (0.0 tests/second)
1 passed, 0 skipped, 1 failed, 1 total error

----

After that, the project should be up and running.

Documentation
-------------

[IMPORTANT]
====
Documentation for the latest release of TestBench (TestBench 2) is still in progress.

For a list of changes from the previous generation (TestBench 1), see link:/doc/Changes-From-TestBench-1-To-TestBench-2.adoc[Changes From TestBench 1 To TestBench 2].

The previous documentation and project can still be found link:https://github.com/test-bench/test-bench-1.x[here].
====

Recent Changes
--------------

For a comprehensive list of changes, see link:/doc/Changes.adoc[Changes]

2.1.0 - Wed Oct 17 2019
^^^^^^^^^^^^^^^^^^^^^^^
* The CLI accepts all of the settings as keyword arguments. Settings supplied to the CLI in this manner will be displayed as the default values by the CLI help text. This allows the CLI settings to be customized on a per-project basis, similar to a per-project configuration file.
* The CLI::Run class accepts the +exclude_file_pattern+ setting as a keyword argument.
* The output methods +enter_assert_block+ and +exit_assert_block+ are now supplied the caller location of the corresponding assertion.
* A bug was fixed in the output implementation that would fail to print outer assertion failures from a block-form assert when the abort on error setting is active.

2.0.0 - Tue Oct 15 2019
^^^^^^^^^^^^^^^^^^^^^^^
The changes from TestBench 1 are too numerous to enumerate. See link:/doc/Changes-From-TestBench-1-To-TestBench-2[Changes From TestBench 1 To TestBench 2] for an overview of the most significant changes.

License
-------

Test Bench is licensed under the link:/MIT-License.txt[MIT license].

Copyright © Nathan Ladd
